### ISSUE TITLE
backend issue

### ISSUE THREAD

**Issue by avijit5442** [manish-mehra/locshare#1]
I just cloned your repo,I am facing with an error please help me.
frontend is working fine but backend giving this issue.

**Comment by avijit5442** [comment]
I just cloned your repo,I am facing with an error please help me.
frontend is working fine but backend giving this issue.
![Screenshot_1](https://github.com/manish-mehra/locshare/assets/94885417/fcdfd27a-19d3-4723-a03a-0fc33dc296c4)

**Comment by manish-mehra** [comment]
@avijit5442  To start the server, do npm run start instead of node index.ts. The typescript need to be compiled first before it can be run with node.js

**Comment by avijit5442** [comment]
I did start with npm run start still it giving error,after that I also changed the file path in package.json by src/index.ts,still giving another error.
NOTE:It is running fine,if we convert ts file to js file by removing type checks in file.But not able to run the old ts file ?
please help me out.

![Screenshot_3](https://github.com/manish-mehra/locshare/assets/94885417/7b1f8e8f-6cca-41b6-8a98-97f732cccfc2)

**Comment by manish-mehra** [comment]
@avijit5442 I don't know Avijit. It works fine on my system. Try setting up the project again.

**Comment by avijit5442** [comment]
Thank you , will try
